language: java
script: gradle assemble
jdk:
- oraclejdk7
- openjdk6
matrix:
        include:
                - jdk: oraclejdk7
                        script: gradle build
                - jdk: openjdk6
                        script: gradle jar
branches:
        only:
                - master
